

@host =  http://localhost:3008





###############users#############
###
#User signup
POST {{host}}/api/v1/users/signup
content-type: application/json

{
  "first_name": "slimane", 
  "last_name": "amiar",
  "email": "slimaneamiar@talik.io",
  "password":  "password",
  "passwordConfirm": "password"
}


###
#User login
POST {{host}}/api/v1/users/login
content-type: application/json

{
  "email": "slimaneamiar@talik.io",
  "password":  "password"
}


###
#get users
GET {{host}}/api/v1/users/
 
###
#Get one user
GET {{host}}/api/v1/users/:id
 



 
###############Comments#############

###
#create a commentfor a given post
POST {{host}}/api/v1/comments/:post_id
content-type: application/json

{
  "post": "p1",
  "content": "t1",
}

###
#get all post comments
GET {{host}}/api/v1/comments/:post_id