version: "3.9"
services:

  #1 Main service
  main_service:
    image: main_service
    build: ./main-service/
    environment:
      NODE_ENV: production
      MODE: docker
      PORT: 7000
    ports:
      - 8000:7000
    depends_on:
      - registry_service
      - rabbitmq_service
    logging:
      driver: "json-file"
      options:
          max-size: "20m"
          max-file: "5"

  #2 registry service
  registry_service:
    image: registry_service
    build: ./registry-service/
    environment:
      NODE_ENV: production
      MODE: docker
      PORT: 7001
    ports:
      - 8001:7001
    logging:
      driver: "json-file"
      options:
          max-size: "20m"
          max-file: "5"

   
  #3 Comments service
  comments_service:
    image: comments_service
    build: ./comments-service/
    environment:
      NODE_ENV: production
      MODE: docker
      PORT: 7002
    ports:
      - 8002:7002
    depends_on:
      - registry_service
      - rabbitmq_service
    logging:
      driver: "json-file"
      options:
          max-size: "20m"
          max-file: "5"

  #4 users service
  users_service:
    image: users_service
    build: ./users-service/
    environment:
      NODE_ENV: production
      MODE: docker
      PORT: 7003
    ports:
      - 8003:7003
    depends_on:
      - registry_service
      - rabbitmq_service
    logging:
      driver: "json-file"
      options:
          max-size: "20m"
          max-file: "5"
  rabbitmq_service:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq_service
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    logging:
      driver: "json-file"
      options:
          max-size: "20m"
          max-file: "5"
  mongo:
    image: mongo
    restart: always
    volumes:
      - ~/.docker-conf/mongo/data/db/:/data/db
      - ~/.docker-conf/mongo/data/configdb/:/data/configdb
 
volumes:
  data: null