@host =  http://localhost:3080


###############Comments#############

###
#create a comment for a given post
POST {{host}}/api/v1/comments/63247ab293a170a9adfb0139
content-type: application/json

{
  "content": "cccccccccc"
}




###
#create a reply for a comment
POST {{host}}/api/v1/comments/63234781046721450235e6ee/comment/63234781046721450235e6ee
content-type: application/json

{
  "content": "this is a repley"
}


###
#get all comments
GET {{host}}/api/v1/comments?limit=100&page=0


###
#get all post comments /post/:post_id
GET {{host}}/api/v1/comments/post/1?page=3



###
#get one comment /:comment_id
GET {{host}}/api/v1/comments/630c5d1e3ebe995222f919f8



{"content": "content 3"}